apiVersion: v1
kind: ConfigMap
metadata:
  name: klovercloud-ci-console-envar-config
  namespace: klovercloud
data:
  v1AuthEndpoint: "http://klovercloud-security.klovercloud.svc.cluster.local/api/v1"
  v1ApiEndPoint: "http://klovercloud-api-service.klovercloud.svc.cluster.local/api/v1"
  v1ApiEndPointWS: "ws://klovercloud-ci-event-bank.klovercloud.svc.cluster.local/api/v1"